import { MealItem, ExerciseItem, MealPlan, WorkoutPlan } from '../types';

// =========================================================================
// FOOD & NUTRITION LIBRARY
// =========================================================================
export const FOOD_LIBRARY: Omit<MealItem, 'id'>[] = [
  // --- Proteins ---
  {
    name: 'Boiled Whole Eggs (2 large)',
    servingSize: '2 eggs (100g)',
    calories: 144,
    protein: 12.6,
    carbs: 0.8,
    fats: 9.6,
    category: 'protein',
    notes: 'Rich in choline, healthy fats, and high-bioavailability protein.',
  },
  {
    name: 'Egg Whites (4 large)',
    servingSize: '130g',
    calories: 68,
    protein: 14.4,
    carbs: 0.9,
    fats: 0.2,
    category: 'protein',
    notes: 'Pure lean protein, zero dietary fat.',
  },
  {
    name: 'Grilled Chicken Breast',
    servingSize: '150g raw weighed',
    calories: 247,
    protein: 46.5,
    carbs: 0,
    fats: 5.4,
    category: 'protein',
    notes: 'Skinless, seasoned with paprika, garlic, and sea salt.',
  },
  {
    name: 'Low-Fat Paneer / Cottage Cheese',
    servingSize: '100g',
    calories: 180,
    protein: 18.0,
    carbs: 4.0,
    fats: 10.0,
    category: 'protein',
    notes: 'Great vegetarian casein protein source for sustained satiety.',
  },
  {
    name: 'Organic Firm Tofu',
    servingSize: '150g',
    calories: 125,
    protein: 15.0,
    carbs: 3.5,
    fats: 6.0,
    category: 'protein',
    notes: 'Plant-based complete protein, pan-seared with low oil.',
  },
  {
    name: 'Whey Protein Isolate',
    servingSize: '1 scoop (30g)',
    calories: 118,
    protein: 26.0,
    carbs: 1.5,
    fats: 0.8,
    category: 'protein',
    notes: 'Rapid absorption post-workout or added to morning oats.',
  },
  {
    name: 'Plant Protein Blend (Pea & Brown Rice)',
    servingSize: '1 scoop (32g)',
    calories: 124,
    protein: 24.0,
    carbs: 2.2,
    fats: 1.8,
    category: 'protein',
    notes: 'Dairy-free vegan protein formulation.',
  },
  {
    name: 'Soya Chunks (Cooked)',
    servingSize: '50g dry weighed',
    calories: 172,
    protein: 26.0,
    carbs: 16.5,
    fats: 0.3,
    category: 'protein',
    notes: 'Boil, squeeze water thoroughly, toss with light spices.',
  },
  {
    name: 'Grilled White Fish (Basa / Rohu / Tilapia)',
    servingSize: '150g',
    calories: 145,
    protein: 31.0,
    carbs: 0,
    fats: 2.5,
    category: 'protein',
    notes: 'Very lean, high protein source easily digestible.',
  },

  // --- Carbohydrates & Whole Grains ---
  {
    name: 'Rolled Oats (Old-fashioned)',
    servingSize: '50g dry',
    calories: 195,
    protein: 6.5,
    carbs: 33.0,
    fats: 3.5,
    category: 'carbs',
    notes: 'Slow-digesting complex carbs rich in beta-glucan fiber.',
  },
  {
    name: 'Steamed Brown Rice',
    servingSize: '1 cup cooked (150g)',
    calories: 168,
    protein: 3.8,
    carbs: 35.0,
    fats: 1.2,
    category: 'carbs',
    notes: 'Mineral-dense grain providing steady energy release.',
  },
  {
    name: 'Steamed Basmati White Rice',
    servingSize: '1 cup cooked (150g)',
    calories: 195,
    protein: 4.1,
    carbs: 43.5,
    fats: 0.4,
    category: 'carbs',
    notes: 'Clean post-workout carbohydrate replenishment.',
  },
  {
    name: 'Whole Wheat Roti / Chapati',
    servingSize: '2 medium rotis (60g flour)',
    calories: 180,
    protein: 5.5,
    carbs: 36.0,
    fats: 1.0,
    category: 'carbs',
    notes: 'Traditional Indian whole wheat flatbread made without oil.',
  },
  {
    name: 'Boiled Sweet Potato',
    servingSize: '150g',
    calories: 130,
    protein: 2.3,
    carbs: 30.0,
    fats: 0.2,
    category: 'carbs',
    notes: 'Rich in Vitamin A, potassium, and slow complex carbohydrates.',
  },
  {
    name: 'Cooked Yellow Moong Dal',
    servingSize: '1 medium bowl (180g)',
    calories: 145,
    protein: 9.0,
    carbs: 22.0,
    fats: 1.8,
    category: 'carbs',
    notes: 'Light on gut digestion with balanced plant protein.',
  },
  {
    name: 'Sprouted Green Moong Beans',
    servingSize: '100g',
    calories: 105,
    protein: 8.0,
    carbs: 18.0,
    fats: 0.6,
    category: 'carbs',
    notes: 'Enzyme-rich raw or steamed snack with lemon & pink salt.',
  },
  {
    name: 'Quinoa (Cooked)',
    servingSize: '1 cup (150g)',
    calories: 185,
    protein: 6.5,
    carbs: 32.0,
    fats: 3.0,
    category: 'carbs',
    notes: 'Gluten-free seed with complete amino acid profile.',
  },

  // --- Healthy Fats & Nuts ---
  {
    name: 'Raw California Almonds',
    servingSize: '15 nuts (18g)',
    calories: 105,
    protein: 3.8,
    carbs: 3.8,
    fats: 9.2,
    category: 'fats',
    notes: 'High in Vitamin E and heart-healthy monounsaturated fats.',
  },
  {
    name: 'Natural Unsweetened Peanut Butter',
    servingSize: '1 tbsp (16g)',
    calories: 95,
    protein: 4.0,
    carbs: 3.2,
    fats: 8.0,
    category: 'fats',
    notes: '100% roasted peanuts with zero added palm oil or sugar.',
  },
  {
    name: 'Walnut Halves',
    servingSize: '6 halves (15g)',
    calories: 98,
    protein: 2.3,
    carbs: 2.0,
    fats: 9.8,
    category: 'fats',
    notes: 'Rich plant-based Omega-3 ALA source for brain health.',
  },
  {
    name: 'Pure Desi Cow Ghee / Olive Oil',
    servingSize: '1 tsp (5g)',
    calories: 45,
    protein: 0,
    carbs: 0,
    fats: 5.0,
    category: 'fats',
    notes: 'Measure accurately with a measuring spoon.',
  },
  {
    name: 'Chia Seeds',
    servingSize: '1 tbsp (12g)',
    calories: 58,
    protein: 2.0,
    carbs: 5.0,
    fats: 3.8,
    category: 'fats',
    notes: 'Soak in water or almond milk for soluble mucilage fiber.',
  },

  // --- Dairy & Alternatives ---
  {
    name: 'Unsweetened Greek Yogurt / Hung Curd',
    servingSize: '150g',
    calories: 110,
    protein: 15.0,
    carbs: 5.5,
    fats: 2.5,
    category: 'dairy',
    notes: 'Probiotic-rich gut support with concentrated protein.',
  },
  {
    name: 'Unsweetened Almond Milk',
    servingSize: '1 glass (240ml)',
    calories: 35,
    protein: 1.2,
    carbs: 1.5,
    fats: 2.8,
    category: 'dairy',
    notes: 'Low-calorie dairy alternative for coffee or protein shakes.',
  },
  {
    name: 'Low-Fat Skimmed Milk',
    servingSize: '1 glass (250ml)',
    calories: 90,
    protein: 8.5,
    carbs: 12.0,
    fats: 0.5,
    category: 'dairy',
    notes: 'Rich in bioavailable calcium and natural whey/casein.',
  },

  // --- Fruits & Veggies ---
  {
    name: 'Crisp Royal Gala Apple',
    servingSize: '1 medium (150g)',
    calories: 78,
    protein: 0.4,
    carbs: 20.0,
    fats: 0.2,
    category: 'veggies',
    notes: 'Eat with skin on for maximum pectin dietary fiber.',
  },
  {
    name: 'Robusta / Elaichi Banana',
    servingSize: '1 medium (100g)',
    calories: 89,
    protein: 1.1,
    carbs: 23.0,
    fats: 0.3,
    category: 'veggies',
    notes: 'Excellent natural pre-workout carb boost 30 mins before training.',
  },
  {
    name: 'Mixed Fresh Cucumber & Tomato Salad',
    servingSize: '1 large bowl (200g)',
    calories: 35,
    protein: 1.5,
    carbs: 6.5,
    fats: 0.4,
    category: 'veggies',
    notes: 'Zero dressing, season with Himalayan pink salt and lemon juice.',
  },
  {
    name: 'Steamed Broccoli & French Beans',
    servingSize: '150g',
    calories: 45,
    protein: 3.5,
    carbs: 8.0,
    fats: 0.5,
    category: 'veggies',
    notes: 'Cruciferous micronutrients with high volume and satiety.',
  },
  {
    name: 'Spinach & Methi Saag (Tossed)',
    servingSize: '150g cooked',
    calories: 55,
    protein: 4.0,
    carbs: 6.0,
    fats: 1.5,
    category: 'veggies',
    notes: 'Rich in iron, magnesium, and dietary antioxidants.',
  },
];

// =========================================================================
// EXERCISE & WORKOUT MOVEMENT LIBRARY
// =========================================================================
export const EXERCISE_LIBRARY: Omit<ExerciseItem, 'id'>[] = [
  // --- Chest ---
  {
    name: 'Barbell Flat Bench Press',
    targetMuscle: 'Chest',
    sets: 3,
    reps: '8-10',
    restSeconds: 90,
    notes: 'Retract scapula, maintain light arch in lower back, drive through feet.',
    videoUrl: 'https://www.youtube.com/watch?v=vcBig73ojpE',
  },
  {
    name: 'Incline Dumbbell Press',
    targetMuscle: 'Chest',
    sets: 3,
    reps: '10-12',
    restSeconds: 75,
    notes: '30-degree incline, control the 2-second negative stretch at bottom.',
    videoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
  },
  {
    name: 'Standing Cable Chest Flyes',
    targetMuscle: 'Chest',
    sets: 3,
    reps: '12-15',
    restSeconds: 60,
    notes: 'Slight bend in elbows, focus on squeezing sternum at contraction.',
    videoUrl: 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
  },
  {
    name: 'Bodyweight Push-Ups',
    targetMuscle: 'Chest',
    sets: 3,
    reps: '15-20',
    restSeconds: 60,
    notes: 'Full depth, chest touches floor, core tightly braced throughout.',
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
  },

  // --- Back ---
  {
    name: 'Wide-Grip Lat Pulldown',
    targetMuscle: 'Back',
    sets: 3,
    reps: '10-12',
    restSeconds: 75,
    notes: 'Pull to upper clavicle, drive elbows down into back pockets.',
    videoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
  },
  {
    name: 'Seated Cable Row (Neutral Grip)',
    targetMuscle: 'Back',
    sets: 3,
    reps: '10-12',
    restSeconds: 75,
    notes: 'Avoid swinging torso, squeeze shoulder blades together for 1 sec.',
    videoUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
  },
  {
    name: 'One-Arm Dumbbell Row',
    targetMuscle: 'Back',
    sets: 3,
    reps: '10-12 per side',
    restSeconds: 60,
    notes: 'Pull toward hip crease, keep flat neutral spine alignment.',
    videoUrl: 'https://www.youtube.com/watch?v=pYcpY20QaE8',
  },
  {
    name: 'Barbell Conventional Deadlift',
    targetMuscle: 'Back',
    sets: 3,
    reps: '5-6',
    restSeconds: 120,
    notes: 'Engage lats to lock bar against shins, push the floor away.',
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
  },
  {
    name: 'Assisted or Full Pull-Ups',
    targetMuscle: 'Back',
    sets: 3,
    reps: '6-10',
    restSeconds: 90,
    notes: 'Dead hang stretch at bottom, chin clears over bar at top.',
    videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
  },

  // --- Shoulders ---
  {
    name: 'Seated Dumbbell Overhead Shoulder Press',
    targetMuscle: 'Shoulders',
    sets: 3,
    reps: '8-10',
    restSeconds: 75,
    notes: 'Keep elbows slightly in front of scapular plane (not flared 90°).',
    videoUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
  },
  {
    name: 'Dumbbell Lateral Raises',
    targetMuscle: 'Shoulders',
    sets: 4,
    reps: '12-15',
    restSeconds: 60,
    notes: 'Lead with elbows, slight forward lean, control the eccentric lower.',
    videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
  },
  {
    name: 'Rear Delt Cable Face Pulls',
    targetMuscle: 'Shoulders',
    sets: 3,
    reps: '15',
    restSeconds: 60,
    notes: 'Pull rope toward eyes with thumbs facing back for rotator cuff health.',
    videoUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
  },

  // --- Legs (Quads, Hamstrings, Glutes, Calves) ---
  {
    name: 'Barbell Back Squat',
    targetMuscle: 'Quads',
    sets: 3,
    reps: '6-8',
    restSeconds: 120,
    notes: 'Break simultaneously at knees and hips, hit parallel depth.',
    videoUrl: 'https://www.youtube.com/watch?v=bEv6CCg2BC8',
  },
  {
    name: 'Dumbbell Walking Lunges',
    targetMuscle: 'Quads',
    sets: 3,
    reps: '12 steps per leg',
    restSeconds: 75,
    notes: 'Take long strides, back knee lightly kisses the ground.',
    videoUrl: 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
  },
  {
    name: 'Leg Press (45-degree sled)',
    targetMuscle: 'Quads',
    sets: 3,
    reps: '10-12',
    restSeconds: 90,
    notes: 'Keep tailbone flat against pad, do not lock out knees aggressively.',
    videoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
  },
  {
    name: 'Romanian Deadlift (Dumbbell or Barbell)',
    targetMuscle: 'Hamstrings',
    sets: 3,
    reps: '10-12',
    restSeconds: 90,
    notes: 'Push hips backward until deep hamstring stretch is felt, soft knees.',
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
  },
  {
    name: 'Lying or Seated Leg Curls',
    targetMuscle: 'Hamstrings',
    sets: 3,
    reps: '12-15',
    restSeconds: 60,
    notes: 'Control movement without lifting hips off the bench.',
    videoUrl: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
  },
  {
    name: 'Barbell / Dumbbell Hip Thrusts',
    targetMuscle: 'Glutes',
    sets: 3,
    reps: '10-12',
    restSeconds: 75,
    notes: 'Chin tucked, full hip extension with 1-second squeeze at apex.',
    videoUrl: 'https://www.youtube.com/watch?v=SEdqd1n0cvg',
  },
  {
    name: 'Standing Calf Raises',
    targetMuscle: 'Calves',
    sets: 4,
    reps: '15-20',
    restSeconds: 45,
    notes: 'Full ankle dorsiflexion stretch, pause 1 second on balls of feet.',
    videoUrl: 'https://www.youtube.com/watch?v=-M4-G8p8fmc',
  },

  // --- Arms (Biceps & Triceps) ---
  {
    name: 'Standing EZ-Bar Bicep Curls',
    targetMuscle: 'Biceps',
    sets: 3,
    reps: '10-12',
    restSeconds: 60,
    notes: 'Pin elbows to ribs, prevent shoulder swinging.',
    videoUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
  },
  {
    name: 'Incline Dumbbell Hammer Curls',
    targetMuscle: 'Biceps',
    sets: 3,
    reps: '12',
    restSeconds: 60,
    notes: 'Targets brachialis and forearms, palms face inwards.',
    videoUrl: 'https://www.youtube.com/watch?v=zC3wV283OcI',
  },
  {
    name: 'Cable Triceps Rope Pushdowns',
    targetMuscle: 'Triceps',
    sets: 3,
    reps: '12-15',
    restSeconds: 60,
    notes: 'Spread rope apart at bottom lockout for peak triceps contraction.',
    videoUrl: 'https://www.youtube.com/watch?v=vB5OHsJ3EME',
  },
  {
    name: 'Overhead Dumbbell Triceps Extension',
    targetMuscle: 'Triceps',
    sets: 3,
    reps: '10-12',
    restSeconds: 60,
    notes: 'Deep stretch on long head of triceps, keep elbows tucked in.',
    videoUrl: 'https://www.youtube.com/watch?v=_gsUck-7M74',
  },

  // --- Core & Conditioning ---
  {
    name: 'Hanging Knee / Leg Raises',
    targetMuscle: 'Core',
    sets: 3,
    reps: '12-15',
    restSeconds: 45,
    notes: 'Curl pelvis up toward chest, do not use momentum swing.',
    videoUrl: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
  },
  {
    name: 'Isometric Forearm Plank Hold',
    targetMuscle: 'Core',
    sets: 3,
    reps: '45-60 sec',
    restSeconds: 45,
    notes: 'Posterior pelvic tilt, glutes clenched, core braced like taking a punch.',
    videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
  },
  {
    name: 'Incline Treadmill Power Walk (12/3/30)',
    targetMuscle: 'Cardio',
    sets: 1,
    reps: '25-30 min',
    restSeconds: 0,
    notes: 'Incline 10-12%, speed 4.5-5.0 km/h, steady zone-2 aerobic fat burning.',
    videoUrl: 'https://www.youtube.com/watch?v=7uV87q_qGjM',
  },
  {
    name: 'HIIT Battle Ropes / Assault Bike Intervals',
    targetMuscle: 'Cardio',
    sets: 8,
    reps: '20s max / 40s rest',
    restSeconds: 40,
    notes: 'All-out anaerobic power output followed by active recovery.',
    videoUrl: 'https://www.youtube.com/watch?v=Kz6E11a14n8',
  },
];

// =========================================================================
// DEFAULT PRESET TEMPLATES
// =========================================================================

export function createDefaultVegDietPlan(userEmail: string, isCoach = false): MealPlan {
  const now = new Date().toISOString();
  return {
    id: `diet_veg_${Date.now()}`,
    name: 'Fitkode High-Protein Vegetarian Fat Loss',
    userId: userEmail,
    userEmail: userEmail,
    targetCalories: 1850,
    targetProtein: 135,
    targetCarbs: 180,
    targetFats: 50,
    dietType: 'Vegetarian',
    createdBy: isCoach ? 'coach' : 'user',
    coachName: isCoach ? 'Chinmay Jain' : undefined,
    coachNotes: isCoach
      ? 'Tailored vegetarian plan focusing on high-satiety plant proteins and complex whole grains. Maintain 3-4L of water daily.'
      : 'Personal high-protein vegetarian meal strategy.',
    isActive: true,
    createdAt: now,
    updatedAt: now,
    meals: [
      {
        id: 'slot_1',
        name: 'Meal 1: High-Protein Morning Oats',
        time: '08:30 AM',
        items: [
          {
            id: 'item_1_1',
            name: 'Rolled Oats (Old-fashioned)',
            servingSize: '50g dry',
            calories: 195,
            protein: 6.5,
            carbs: 33.0,
            fats: 3.5,
            category: 'carbs',
          },
          {
            id: 'item_1_2',
            name: 'Whey Protein Isolate',
            servingSize: '1 scoop (30g)',
            calories: 118,
            protein: 26.0,
            carbs: 1.5,
            fats: 0.8,
            category: 'protein',
          },
          {
            id: 'item_1_3',
            name: 'Raw California Almonds',
            servingSize: '10 nuts (12g)',
            calories: 70,
            protein: 2.5,
            carbs: 2.5,
            fats: 6.1,
            category: 'fats',
          },
        ],
      },
      {
        id: 'slot_2',
        name: 'Meal 2: Mid-Day Snack & Fruit',
        time: '11:30 AM',
        items: [
          {
            id: 'item_2_1',
            name: 'Unsweetened Greek Yogurt / Hung Curd',
            servingSize: '150g',
            calories: 110,
            protein: 15.0,
            carbs: 5.5,
            fats: 2.5,
            category: 'dairy',
          },
          {
            id: 'item_2_2',
            name: 'Crisp Royal Gala Apple',
            servingSize: '1 medium (150g)',
            calories: 78,
            protein: 0.4,
            carbs: 20.0,
            fats: 0.2,
            category: 'veggies',
          },
        ],
      },
      {
        id: 'slot_3',
        name: 'Meal 3: Nourishing Balanced Lunch',
        time: '01:45 PM',
        items: [
          {
            id: 'item_3_1',
            name: 'Low-Fat Paneer / Cottage Cheese',
            servingSize: '120g grilled',
            calories: 216,
            protein: 21.6,
            carbs: 4.8,
            fats: 12.0,
            category: 'protein',
          },
          {
            id: 'item_3_2',
            name: 'Steamed Brown Rice',
            servingSize: '1 cup cooked (150g)',
            calories: 168,
            protein: 3.8,
            carbs: 35.0,
            fats: 1.2,
            category: 'carbs',
          },
          {
            id: 'item_3_3',
            name: 'Cooked Yellow Moong Dal',
            servingSize: '1 medium bowl (180g)',
            calories: 145,
            protein: 9.0,
            carbs: 22.0,
            fats: 1.8,
            category: 'carbs',
          },
          {
            id: 'item_3_4',
            name: 'Mixed Fresh Cucumber & Tomato Salad',
            servingSize: '1 large bowl (200g)',
            calories: 35,
            protein: 1.5,
            carbs: 6.5,
            fats: 0.4,
            category: 'veggies',
          },
        ],
      },
      {
        id: 'slot_4',
        name: 'Meal 4: Pre-Workout Fuel',
        time: '05:30 PM',
        items: [
          {
            id: 'item_4_1',
            name: 'Robusta / Elaichi Banana',
            servingSize: '1 medium (100g)',
            calories: 89,
            protein: 1.1,
            carbs: 23.0,
            fats: 0.3,
            category: 'veggies',
          },
          {
            id: 'item_4_2',
            name: 'Natural Unsweetened Peanut Butter',
            servingSize: '1 tbsp (16g)',
            calories: 95,
            protein: 4.0,
            carbs: 3.2,
            fats: 8.0,
            category: 'fats',
          },
        ],
      },
      {
        id: 'slot_5',
        name: 'Meal 5: Light High-Protein Dinner',
        time: '08:30 PM',
        items: [
          {
            id: 'item_5_1',
            name: 'Organic Firm Tofu',
            servingSize: '150g tossed',
            calories: 125,
            protein: 15.0,
            carbs: 3.5,
            fats: 6.0,
            category: 'protein',
          },
          {
            id: 'item_5_2',
            name: 'Whole Wheat Roti / Chapati',
            servingSize: '2 rotis (60g)',
            calories: 180,
            protein: 5.5,
            carbs: 36.0,
            fats: 1.0,
            category: 'carbs',
          },
          {
            id: 'item_5_3',
            name: 'Spinach & Methi Saag (Tossed)',
            servingSize: '150g',
            calories: 55,
            protein: 4.0,
            carbs: 6.0,
            fats: 1.5,
            category: 'veggies',
          },
        ],
      },
    ],
  };
}

export function createDefaultWorkoutPlan(userEmail: string, isCoach = false): WorkoutPlan {
  const now = new Date().toISOString();
  return {
    id: `workout_ppl_${Date.now()}`,
    name: '4-Day Hypertrophy & Strength Split',
    userId: userEmail,
    userEmail: userEmail,
    difficulty: 'Intermediate',
    goal: 'Hypertrophy & Muscle Gain',
    daysPerWeek: 4,
    createdBy: isCoach ? 'coach' : 'user',
    coachName: isCoach ? 'Chinmay Jain' : undefined,
    coachNotes: isCoach
      ? 'Perform progressive overload: note your weights each week. Warm up with 5 minutes dynamic arm swings and hip openers before heavy compounds.'
      : 'My 4-day structured gym program.',
    isActive: true,
    createdAt: now,
    updatedAt: now,
    days: [
      {
        id: 'day_1',
        dayName: 'Day 1: Push (Chest, Shoulders & Triceps)',
        isRestDay: false,
        focus: 'Upper Push Hypertrophy',
        exercises: [
          {
            id: 'ex_1_1',
            name: 'Barbell Flat Bench Press',
            targetMuscle: 'Chest',
            sets: 3,
            reps: '8-10',
            restSeconds: 90,
            notes: 'Pause 1s on chest, drive bar explosively.',
            videoUrl: 'https://www.youtube.com/watch?v=vcBig73ojpE',
          },
          {
            id: 'ex_1_2',
            name: 'Incline Dumbbell Press',
            targetMuscle: 'Chest',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
            notes: '30-degree angle, focus on upper chest stretch.',
            videoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
          },
          {
            id: 'ex_1_3',
            name: 'Seated Dumbbell Overhead Shoulder Press',
            targetMuscle: 'Shoulders',
            sets: 3,
            reps: '8-10',
            restSeconds: 75,
            notes: 'Elbows slightly tucked in front.',
            videoUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
          },
          {
            id: 'ex_1_4',
            name: 'Dumbbell Lateral Raises',
            targetMuscle: 'Shoulders',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
            notes: 'Control the descent for 2 seconds.',
            videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
          },
          {
            id: 'ex_1_5',
            name: 'Cable Triceps Rope Pushdowns',
            targetMuscle: 'Triceps',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
            notes: 'Spread rope apart at bottom.',
            videoUrl: 'https://www.youtube.com/watch?v=vB5OHsJ3EME',
          },
        ],
      },
      {
        id: 'day_2',
        dayName: 'Day 2: Pull (Back, Rear Delts & Biceps)',
        isRestDay: false,
        focus: 'Upper Pull & Posterior Upper',
        exercises: [
          {
            id: 'ex_2_1',
            name: 'Wide-Grip Lat Pulldown',
            targetMuscle: 'Back',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
            notes: 'Pull to upper clavicle, squeeze lats.',
            videoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
          },
          {
            id: 'ex_2_2',
            name: 'Seated Cable Row (Neutral Grip)',
            targetMuscle: 'Back',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
            notes: 'Torso remains upright, squeeze rhomboids.',
            videoUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
          },
          {
            id: 'ex_2_3',
            name: 'Rear Delt Cable Face Pulls',
            targetMuscle: 'Shoulders',
            sets: 3,
            reps: '15',
            restSeconds: 60,
            notes: 'Pull to eye level, external shoulder rotation.',
            videoUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
          },
          {
            id: 'ex_2_4',
            name: 'Standing EZ-Bar Bicep Curls',
            targetMuscle: 'Biceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
            notes: 'Keep elbows glued to sides.',
            videoUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
          },
          {
            id: 'ex_2_5',
            name: 'Incline Dumbbell Hammer Curls',
            targetMuscle: 'Biceps',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            notes: 'Full bicep stretch on incline bench.',
            videoUrl: 'https://www.youtube.com/watch?v=zC3wV283OcI',
          },
        ],
      },
      {
        id: 'day_3',
        dayName: 'Day 3: Rest & Active Mobility Recovery',
        isRestDay: true,
        focus: 'Rest, 8,000 steps & Hip Mobility',
        exercises: [
          {
            id: 'ex_3_1',
            name: 'Incline Treadmill Power Walk (12/3/30)',
            targetMuscle: 'Cardio',
            sets: 1,
            reps: '30 min',
            restSeconds: 0,
            notes: 'Zone 2 steady recovery walk, listen to a podcast.',
            videoUrl: 'https://www.youtube.com/watch?v=7uV87q_qGjM',
          },
        ],
      },
      {
        id: 'day_4',
        dayName: 'Day 4: Legs & Core Strength',
        isRestDay: false,
        focus: 'Quad, Hamstring & Abdominal Development',
        exercises: [
          {
            id: 'ex_4_1',
            name: 'Barbell Back Squat',
            targetMuscle: 'Quads',
            sets: 3,
            reps: '6-8',
            restSeconds: 120,
            notes: 'Deep breath and brace core before each rep.',
            videoUrl: 'https://www.youtube.com/watch?v=bEv6CCg2BC8',
          },
          {
            id: 'ex_4_2',
            name: 'Romanian Deadlift (Dumbbell or Barbell)',
            targetMuscle: 'Hamstrings',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
            notes: 'Feel deep stretch in hamstrings, flat back.',
            videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
          },
          {
            id: 'ex_4_3',
            name: 'Dumbbell Walking Lunges',
            targetMuscle: 'Quads',
            sets: 3,
            reps: '12 steps per leg',
            restSeconds: 75,
            notes: 'Upright torso, knee 1 inch off floor.',
            videoUrl: 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
          },
          {
            id: 'ex_4_4',
            name: 'Hanging Knee / Leg Raises',
            targetMuscle: 'Core',
            sets: 3,
            reps: '12-15',
            restSeconds: 45,
            notes: 'Raise knees to sternum, controlled lower.',
            videoUrl: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
          },
          {
            id: 'ex_4_5',
            name: 'Isometric Forearm Plank Hold',
            targetMuscle: 'Core',
            sets: 3,
            reps: '60 sec',
            restSeconds: 45,
            notes: 'Squeeze glutes and press through forearms.',
            videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
          },
        ],
      },
    ],
  };
}
